services:
  mysql:
    image: mysql:8.0
    container_name: sd_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root123456
      MYSQL_DATABASE: sd_photo
      MYSQL_USER: sd_user
      MYSQL_PASSWORD: sd_pass
    ports:
      - "3306:3306"
    command: ["mysqld", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
